services:
  - type: web
    name: krishisat-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: ML_SERVICE_URL
        value: https://krishisat-ai.onrender.com
      - key: JWT_SECRET
        sync: false
