services:
  - type: web
    name: krishisat-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: ML_SERVICE_URL
        value: https://krishisat-ml.onrender.com
      - key: JWT_SECRET
        sync: false
